/**
 * FIMFORTE SPECIALIST HOSPITAL — ACCREDITED HMO & INSURANCE DIRECTORY
 * Officially supported Health Maintenance Organizations (HMOs) & Health Schemes
 * Verified with official online logo & brand icon assets
 */

const HMO_DIRECTORY = [
  {
    id: "reliance",
    name: "Reliance HMO",
    shortCode: "RELIANCE",
    category: "Digital / Private",
    tier: "Red, Blue & Corporate Plans",
    status: "active",
    badge: "Fast-Track Approval",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://getreliancehealth.com&size=128",
    website: "https://getreliancehealth.com",
    coverage: "Outpatient, Emergency, Antenatal Clinic, Child Immunization, Prescription Drugs",
    notes: "Instant digital code verification through the Reliance HMO mobile app.",
    preAuth: false,
    keywords: ["reliance", "reliance hmo", "reliance health", "digital hmo"]
  },
  {
    id: "hygeia",
    name: "Hygeia HMO",
    shortCode: "HYGEIA",
    category: "Private / Corporate",
    tier: "All Comprehensive Plans",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://hygeiahmo.com&size=128",
    website: "https://hygeiahmo.com",
    coverage: "Obstetrics & Gynaecology, General Surgery, Paediatrics, Neonatal Care, In-house Laboratory",
    notes: "Instant real-time portal clearance for eligible plan holders.",
    preAuth: false,
    keywords: ["hygeia", "hygeia hmo", "corporate", "hygeia health"]
  },
  {
    id: "ihms",
    name: "IHMS (International Health Management Services)",
    shortCode: "IHMS",
    category: "Private / Corporate",
    tier: "Corporate & Individual Plans",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://ihmsnigeria.com&size=128",
    website: "https://ihmsnigeria.com",
    coverage: "Specialist Care, Inpatient Admission, Maternity, Diagnostic Testing, Surgery",
    notes: "Active provider clearance via IHMS member authorization portal.",
    preAuth: false,
    keywords: ["ihms", "international health management", "ihms hmo", "ihms healthcare"]
  },
  {
    id: "hci",
    name: "HCI Healthcare (HCI HMO)",
    shortCode: "HCI",
    category: "Private / Corporate",
    tier: "Standard & Executive Plans",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://hcihealthcare.ng&size=128",
    website: "https://hcihealthcare.ng",
    coverage: "Antenatal & Maternity Delivery, General Surgery, Paediatrics, Emergency Admissions",
    notes: "Direct verification with HCI membership card or authorization code.",
    preAuth: false,
    keywords: ["hci", "hci healthcare", "hci hmo"]
  },
  {
    id: "hyssop",
    name: "Hyssop HMO",
    shortCode: "HYSSOP",
    category: "Private / Corporate",
    tier: "Comprehensive Health Plans",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://hyssophmo.com&size=128",
    website: "https://hyssophmo.com",
    coverage: "General Consultations, Obstetrics, Child Care, Diagnostic Lab, Surgery",
    notes: "Seamless intake verification for registered policyholders.",
    preAuth: false,
    keywords: ["hyssop", "hyssop hmo", "hyssop health"]
  },
  {
    id: "leadway",
    name: "Leadway Health HMO",
    shortCode: "LEADWAY",
    category: "Private / Corporate",
    tier: "Standard, Premier & Executive",
    status: "active",
    badge: "Fast-Track Approval",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://leadway.com&size=128",
    website: "https://leadway.com",
    coverage: "General Consultations, Obstetrics, Advanced Surgical Procedures, Laboratory Diagnostics",
    notes: "Corporate retainership and private individual policies accepted.",
    preAuth: false,
    keywords: ["leadway", "leadway health", "leadway hmo"]
  },
  {
    id: "bastion",
    name: "Bastion HMO",
    shortCode: "BASTION",
    category: "Digital / Private",
    tier: "Classic, Gold & Corporate",
    status: "active",
    badge: "Fast-Track Approval",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://bastionhmo.com&size=128",
    website: "https://bastionhmo.com",
    coverage: "Antenatal Care, Delivery, Child Clinic, Inpatient Admissions, Surgical Care",
    notes: "Digital QR code or policy number authentication accepted.",
    preAuth: false,
    keywords: ["bastion", "bastion hmo", "bastion health"]
  },
  {
    id: "anchor",
    name: "Anchor HMO International",
    shortCode: "ANCHOR",
    category: "Private / Corporate",
    tier: "Corporate & Retail Tiers",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://portal.anchorhmo.com&size=128",
    website: "https://anchorhmo.com",
    coverage: "General Practice, Specialist Consultations, Lab Investigations, Paediatrics",
    notes: "Valid member card or digital authorization code required.",
    preAuth: false,
    keywords: ["anchor", "anchor hmo", "anchor international"]
  },
  {
    id: "springtide",
    name: "Springtide HMO",
    shortCode: "SPRINGTIDE",
    category: "Private / Corporate",
    tier: "Corporate & Individual Plans",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://springtidehmo.com&size=128",
    website: "https://springtidehmo.com",
    coverage: "Inpatient Care, Maternal Health, Pediatrics, Casualty & Diagnostics",
    notes: "Direct verification via Springtide enrollee portal.",
    preAuth: false,
    keywords: ["springtide", "springtide hmo", "spring tide"]
  },
  {
    id: "synergy",
    name: "Synergy HMO",
    shortCode: "SYNERGY",
    category: "Private / Corporate",
    tier: "All Enrollee Tiers",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://synergywellcare.com&size=128",
    website: "https://synergywellcare.com",
    coverage: "Outpatient & Inpatient, Maternity, Childcare, Lab Investigations",
    notes: "Fast front-desk authorization for eligible policyholders.",
    preAuth: false,
    keywords: ["synergy", "synergy hmo", "synergy healthcare"]
  },
  {
    id: "mbo",
    name: "MB & O Healthcare Services",
    shortCode: "MB&O",
    category: "Private / Corporate",
    tier: "Tier 1 Specialist Provider",
    status: "active",
    badge: "Tier 1 Partner",
    badgeColor: "emerald",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://mbandohmo.com&size=128",
    website: "https://mbandohmo.com",
    coverage: "Full Comprehensive Hospitalization, Maternal Care, Intensive Care, Specialist Surgeries",
    notes: "Direct clinical retainership agreement with priority triage.",
    preAuth: false,
    keywords: ["mb & o", "mbo", "mb and o", "mb&o", "mb&o healthcare"]
  },
  {
    id: "oceanic",
    name: "Oceanic Health HMO",
    shortCode: "OCEANIC",
    category: "Private / Corporate",
    tier: "Corporate & Retail Plans",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://oceanichealth.com&size=128",
    website: "https://oceanichealth.com",
    coverage: "Obstetrics & Gynaecology, Surgeries, Inpatient Admissions, Diagnostics",
    notes: "Immediate portal check-in with Oceanic policy ID.",
    preAuth: false,
    keywords: ["oceanic", "oceanic health", "oceanic hmo"]
  },
  {
    id: "dot",
    name: "Dot HMO",
    shortCode: "DOT",
    category: "Digital / Private",
    tier: "Digital Retail & Corporate",
    status: "active",
    badge: "Fast-Track Approval",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://dothmo.co&size=128",
    website: "https://dothmo.co",
    coverage: "Consultations, Antenatal, Child Clinic, Inpatient Care, Pharmacy",
    notes: "Instant digital authorization via Dot mobile platform.",
    preAuth: false,
    keywords: ["dot", "dot hmo", "dot health", "digital hmo"]
  },
  {
    id: "united-health",
    name: "United Healthcare International",
    shortCode: "UNITED HEALTH",
    category: "Private / Corporate",
    tier: "Executive & Corporate Plans",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://uhc.com&size=128",
    website: "https://uhc.com",
    coverage: "Comprehensive Care, Surgeries, High-Risk Obstetrics, Paediatrics, Diagnostics",
    notes: "Accepted for national and multinational corporate staff.",
    preAuth: false,
    keywords: ["united health", "united healthcare", "united healthcare international", "uhc"]
  },
  {
    id: "mediplan",
    name: "Mediplan Healthcare",
    shortCode: "MEDIPLAN",
    category: "Private / Corporate",
    tier: "Comprehensive Plans",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://mediplanhealthcare.com&size=128",
    website: "https://mediplanhealthcare.com",
    coverage: "General Consultations, Maternity, Laboratory Investigations, Child Care",
    notes: "Verification supported at front desk with Mediplan enrollee ID.",
    preAuth: false,
    keywords: ["mediplan", "mediplan healthcare", "mediplan hmo"]
  },
  {
    id: "nem",
    name: "NEM Health HMO",
    shortCode: "NEM",
    category: "Private / Corporate",
    tier: "Individual & Group Policies",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nem-health.com&size=128",
    website: "https://nem-health.com",
    coverage: "Outpatient Services, Emergency Care, Maternity Delivery, Specialist Visits",
    notes: "Fast-track authorization through NEM Health portal.",
    preAuth: false,
    keywords: ["nem", "nem health", "nem hmo", "nem insurance"]
  },
  {
    id: "avon",
    name: "Avon HMO",
    shortCode: "AVON",
    category: "Private / Corporate",
    tier: "All Plans (Individual & Corporate)",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://avonhealthcare.com&size=128",
    website: "https://avonhealthcare.com",
    coverage: "Maternal Care, Normal & Caesarean Delivery, Paediatrics, Specialist Physician Consultations, General Surgery",
    notes: "Direct desk authentication via Avon mobile app code or HMO card.",
    preAuth: false,
    keywords: ["avon", "avon hmo", "avon healthcare", "corporate"]
  },
  {
    id: "rivchpp",
    name: "RIVCHPP (Rivers State Contributory Health Protection Programme)",
    shortCode: "RIVCHPP",
    category: "NHIS / Government",
    tier: "Rivers State Government Health Scheme",
    status: "active",
    badge: "State Government Scheme",
    badgeColor: "emerald",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://rivchpp.rv.gov.ng&size=128",
    website: "https://rivchpp.rv.gov.ng",
    coverage: "Antenatal & Maternity Care, Child Health, Emergency Intake, Chronic Disease Management, Basic Surgeries",
    notes: "Official accredited provider for Rivers State civil servants and enrolled community residents.",
    preAuth: false,
    keywords: ["rivchpp", "rivers state", "rivers state contributory health", "state scheme", "rivers state health", "port harcourt"]
  },
  {
    id: "clearline",
    name: "Clearline HMO",
    shortCode: "CLEARLINE",
    category: "Private / Corporate",
    tier: "All Standard Plans",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://clearlinehmo.com&size=128",
    website: "https://clearlinehmo.com",
    coverage: "Antenatal Clinics, Normal Deliveries, Routine Paediatrics, Inpatient Recovery",
    notes: "Walk-in verification available during administrative clinic hours.",
    preAuth: false,
    keywords: ["clearline", "clearline hmo", "clear line"]
  },
  {
    id: "health-assur",
    name: "Health Assur HMO",
    shortCode: "HEALTH ASSUR",
    category: "Private / Corporate",
    tier: "Corporate & Retail Tiers",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://healthassur.com&size=128",
    website: "https://healthassur.com",
    coverage: "Specialist Care, Inpatient Admission, Maternal Healthcare, In-House Diagnostics",
    notes: "Portal authentication supported with Health Assur member number.",
    preAuth: false,
    keywords: ["health assur", "healthassur", "health assur hmo"]
  },
  {
    id: "alleanza",
    name: "Alleanza Healthcare",
    shortCode: "ALLEANZA",
    category: "Private / Corporate",
    tier: "Standard & Executive Tiers",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://alleanzahealth.com&size=128",
    website: "https://alleanzahealth.com",
    coverage: "Consultations, Maternity Delivery, Pediatrics, General Surgery, Diagnostics",
    notes: "Direct verification with Alleanza authorization card.",
    preAuth: false,
    keywords: ["alleanza", "alleanza healthcare", "alleanza hmo"]
  },
  {
    id: "medical-partners",
    name: "Medical Partners HMO",
    shortCode: "MEDICAL PARTNERS",
    category: "Private / Corporate",
    tier: "Standard & Executive",
    status: "active",
    badge: "Accredited Partner",
    badgeColor: "teal",
    logo: "https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://medicalpartners.ng&size=128",
    website: "https://medicalpartners.ng",
    coverage: "General Medicine, Obstetrics, Diagnostics, Routine Surgeries",
    notes: "Accepted across outpatient and emergency admissions.",
    preAuth: false,
    keywords: ["medical partners", "medical partners hmo", "med partners"]
  },
  {
    id: "corporate-retainership",
    name: "Corporate Retainerships (Oil, Gas & Energy)",
    shortCode: "RETAINERSHIP",
    category: "Corporate Retainership",
    tier: "Direct Hospital Retainership",
    status: "active",
    badge: "Priority Direct Desk",
    badgeColor: "emerald",
    logo: "assets/icons/fimforte-favicon.svg",
    website: "https://fimfortehospital.ng",
    coverage: "Full Family Coverage, Executive Health Screenings, Emergency Evacuation, Surgery, Maternity",
    notes: "Companies registered under Fimforte direct billing retainership protocols.",
    preAuth: false,
    keywords: ["corporate", "retainership", "oil and gas", "company health", "staff insurance", "company retainer"]
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { HMO_DIRECTORY };
}
